import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import type { CDNLibrary } from '../types/editor.types';
import { PRODUCT_NAME, DEFAULT_EXPORT_PREFIX } from '../constants/branding';
import { getPlatformBridge } from './platformBridge';

export async function buildProjectZip(
  html: string,
  css: string,
  js: string,
  activeLibraries: CDNLibrary[] = [],
  projectName = DEFAULT_EXPORT_PREFIX,
): Promise<{ blob: Blob; filename: string }> {
  const zip = new JSZip();
  const libraryTags = activeLibraries.map((lib) => `    ${lib.tag}`).join('\n');

  zip.file(
    'index.html',
    `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${projectName}</title>
${libraryTags}
    <link rel="stylesheet" href="style.css">
</head>
<body>
    ${html}
    <script defer src="script.js"><\/script>
</body>
</html>`,
  );

  zip.file('style.css', css);
  zip.file('script.js', js);
  zip.file('README.md', `# ${projectName}\n\nGenerated by ${PRODUCT_NAME}.\n`);

  const blob = await zip.generateAsync({ type: 'blob' });
  return { blob, filename: `${projectName}.zip` };
}

export async function exportProject(
  html: string,
  css: string,
  js: string,
  activeLibraries: CDNLibrary[] = [],
  projectName = DEFAULT_EXPORT_PREFIX,
) {
  const { blob, filename } = await buildProjectZip(html, css, js, activeLibraries, projectName);
  const bridge = await getPlatformBridge();

  if (bridge.isDesktop) {
    const saved = await bridge.exportZip(blob, filename);
    if (saved) return;
  }

  saveAs(blob, filename);
}
