import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import type { CDNLibrary } from '../types/editor.types';

export async function exportProject(
  html: string,
  css: string,
  js: string,
  activeLibraries: CDNLibrary[] = [],
  projectName = 'liveview-project',
) {
  const zip = new JSZip();

  const libraryTags = activeLibraries.map((lib) => `    ${lib.tag}`).join('\n');

  zip.file(
    'index.html',
    `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${projectName}</title>
${libraryTags}
    <link rel="stylesheet" href="style.css">
</head>
<body>
    ${html}
    <script defer src="script.js"><\/script>
</body>
</html>`,
  );

  zip.file('style.css', css);
  zip.file('script.js', js);
  zip.file('README.md', `# ${projectName}\n\nGenerated by LiveView Notepad.\n`);

  const blob = await zip.generateAsync({ type: 'blob' });
  saveAs(blob, `${projectName}.zip`);
}
