import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import type { CDNLibrary } from '../types/editor.types';
import { PRODUCT_NAME, DEFAULT_EXPORT_PREFIX } from '../constants/branding';
import { isDesktop } from './platformBridge';

export async function exportProject(
  html: string,
  css: string,
  js: string,
  activeLibraries: CDNLibrary[] = [],
  projectName = DEFAULT_EXPORT_PREFIX,
): Promise<boolean> {
  const zip = new JSZip();

  const libraryTags = activeLibraries.map((lib) => `    ${lib.tag}`).join('\n');

  zip.file(
    'index.html',
    `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${projectName}</title>
${libraryTags}
    <link rel="stylesheet" href="style.css">
</head>
<body>
    ${html}
    <script defer src="script.js"><\/script>
</body>
</html>`,
  );

  zip.file('style.css', css);
  zip.file('script.js', js);
  zip.file('README.md', `# ${projectName}\n\nGenerated by ${PRODUCT_NAME}.\n`);

  const blob = await zip.generateAsync({ type: 'blob' });
  const filename = `${projectName}.zip`;

  if (isDesktop()) {
    const { save } = await import('@tauri-apps/plugin-dialog');
    const { writeFile } = await import('@tauri-apps/plugin-fs');
    const path = await save({
      filters: [{ name: 'ZIP Archive', extensions: ['zip'] }],
      defaultPath: filename,
    });
    if (!path) return false;

    const buffer = await blob.arrayBuffer();
    await writeFile(path, new Uint8Array(buffer));
    return true;
  }

  saveAs(blob, filename);
  return true;
}
